[package]
name = "sgdktool"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
dirs = "5"
toml_edit = "0.21"
which = "5"
fs_extra = "1.3"
reqwest = { version = "0.12.20", features = ["blocking"] }
rust-i18n = "3"
